### PR TITLE
Feature/iterable

### PR DESCRIPTION
**Pull request by vvval**
- fix `iterable` type hint

### CODE REVIEW

**Comment by wolfy-j** [comment]
So I can't pass the API repository as input?

**Comment by vvval** [comment]
> So I can't pass the API repository as input?

Ok, then I'll throw an exception if after compiling we get a non-iterable variable. Will this work for you?

**Comment by wolfy-j** [comment]
yes exception will work

**Comment by vvval** [comment]
Throwing an exception if after creating a grid view the source is still not iterable

**Pull request merged**
